name: expense_repository
description: Repo that handle user


publish_to: 'none' 
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter 


  cupertino_icons: ^1.0.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.9.2
  #rxdart: ^0.27.7
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true